# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awswitch < Formula
  desc "A helper utility for switching AWS profiles in subshells."
  homepage "https://github.com/ArcadiaPower/awswitch/"
  version "1.0.4"
  license "MIT"

  depends_on "gimme-aws-creds"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArcadiaPower/awswitch/releases/download/v1.0.4/awswitch_1.0.4_darwin_arm64.tar.gz"
      sha256 "e0e4dfcc3c41200f6b0415d433b294c2b4e6ccbfafd4b5b810084e29219d3bc6"

      def install
        bin.install "awswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArcadiaPower/awswitch/releases/download/v1.0.4/awswitch_1.0.4_linux_arm64.tar.gz"
      sha256 "cba2c64b95919f9acb0046f14f395d2e8f6001a180559c2b9eddb173ffd2c32c"

      def install
        bin.install "awswitch"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completion add the following line to your #{shell_profile}:
      	BASH:
      	eval "$(awswitch --completion-script-bash)"
      	ZSH:
      	eval "$(awswitch --completion-script-zsh)"

      Restart your terminal for the settings to take effect.
    EOS
  end

  test do
    system "#{bin}/awswitch --version"
  end
end
