# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axolotl < Formula
  desc "A helper utility for switching AWS profiles in subshells."
  homepage "https://github.com/ArcadiaPower/axolotl/"
  version "1.0.5-rc1"
  license "MIT"

  depends_on "gimme-aws-creds"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.5-rc1/axolotl_1.0.5-rc1_darwin_arm64.tar.gz"
      sha256 "ed83c4cffe27d4b0563b6bffc64d2818f4b927f2e58b2a54643a552bf52891da"

      def install
        bin.install "ax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.5-rc1/axolotl_1.0.5-rc1_linux_arm64.tar.gz"
      sha256 "8dc58100872f09af15f0d21d5768f84e161371a674d6d1a1763efa295a68689e"

      def install
        bin.install "ax"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completion add the following line to your #{shell_profile}:
      	BASH:
      	eval "$(ax --completion-script-bash)"
      	ZSH:
      	eval "$(ax --completion-script-zsh)"

      Restart your terminal for the settings to take effect.
    EOS
  end

  test do
    system "#{bin}/ax --version"
  end
end
