# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axolotl < Formula
  desc "A helper utility for switching AWS profiles in subshells."
  homepage "https://github.com/ArcadiaPower/axolotl/"
  version "1.1.0"
  license "MIT"

  depends_on "gimme-aws-creds"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.1.0/axolotl_1.1.0_macOS_arm64.tar.gz"
      sha256 "cf106513d745160dc9eed0a1f500033ad95fbb9aed88f308152903c338a947a5"

      def install
        bin.install "ax"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.1.0/axolotl_1.1.0_macOS_x86_64.tar.gz"
      sha256 "86a7a8b3c6c64a3885ef09b1b49ac0df355cf461b8c9025b44be10bd0cff5178"

      def install
        bin.install "ax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.1.0/axolotl_1.1.0_linux_arm64.tar.gz"
      sha256 "28a0781fcdd4d5a4f13c49a7a59458c011e5ed9548a2de05efa43f8002b20207"

      def install
        bin.install "ax"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.1.0/axolotl_1.1.0_linux_x86_64.tar.gz"
      sha256 "43b71e6fbddaadc2dd6a7b541c503473f3ca4f57bebcca857bc61712923ebdca"

      def install
        bin.install "ax"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completion add the following line to your #{shell_profile}:
      	BASH:
      	eval "$(ax --completion-script-bash)"
      	ZSH:
      	eval "$(ax --completion-script-zsh)"

      Restart your terminal for the settings to take effect.
    EOS
  end

  test do
    system "#{bin}/ax --version"
  end
end
