# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axolotl < Formula
  desc "A helper utility for switching AWS profiles in subshells."
  homepage "https://github.com/ArcadiaPower/axolotl/"
  version "1.0.6"
  license "MIT"

  depends_on "gimme-aws-creds"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.6/axolotl_1.0.6_macOS_arm64.tar.gz"
      sha256 "b7c96f3cc2ebf4cb82fbeaab1c54442997023573210969c19ce197efb52b770d"

      def install
        bin.install "ax"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.6/axolotl_1.0.6_macOS_x86_64.tar.gz"
      sha256 "ea18568be885a417e70518f59e9234d2ddbba5473deef5fd7c0d2ca26bee9576"

      def install
        bin.install "ax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.6/axolotl_1.0.6_linux_x86_64.tar.gz"
      sha256 "bfc3c3a5eeb8afff27e866a165598a99ead70f07fbb408f321705e7afb5ac751"

      def install
        bin.install "ax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArcadiaPower/axolotl/releases/download/v1.0.6/axolotl_1.0.6_linux_arm64.tar.gz"
      sha256 "a81a8a44222a97605f1d2f238be38fc89979d2814681e5ae6f7dca313196a0e9"

      def install
        bin.install "ax"
      end
    end
  end

  def caveats
    <<~EOS
      To install shell completion add the following line to your #{shell_profile}:
      	BASH:
      	eval "$(ax --completion-script-bash)"
      	ZSH:
      	eval "$(ax --completion-script-zsh)"

      Restart your terminal for the settings to take effect.
    EOS
  end

  test do
    system "#{bin}/ax --version"
  end
end
